git mv bp-stats-review-2022-consolidated-dataset-panel-format.csv /home/burak/Documents/thirdwave/en/2022/01
git mv coal.png /home/burak/Documents/thirdwave/en/2022/01
git mv countries.csv /home/burak/Documents/thirdwave/en/2022/01
git mv energstats.md /home/burak/Documents/thirdwave/en/2022/01
git mv energy-sources.png /home/burak/Documents/thirdwave/en/2022/01
git mv eqfaults.py /home/burak/Documents/thirdwave/en/2022/01
git mv lng.csv /home/burak/Documents/thirdwave/en/2022/01
git mv lng.png /home/burak/Documents/thirdwave/en/2022/01
git mv lumber.png /home/burak/Documents/thirdwave/en/2022/01
git mv mineral_base.csv /home/burak/Documents/thirdwave/en/2022/01
git mv mineral-coal.csv /home/burak/Documents/thirdwave/en/2022/01
git mv mineral_iaea_geo_ur.csv /home/burak/Documents/thirdwave/en/2022/01
git mv mineral_iaea_ur.csv /home/burak/Documents/thirdwave/en/2022/01
git mv minerals-out.html /home/burak/Documents/thirdwave/en/2022/01
git mv minerals.py /home/burak/Documents/thirdwave/en/2022/01
git mv natgas.png /home/burak/Documents/thirdwave/en/2022/01
git mv oilgas-2018.csv /home/burak/Documents/thirdwave/en/2022/01
git mv oilgasmin.md /home/burak/Documents/thirdwave/en/2022/01
git mv oilgas-out.html /home/burak/Documents/thirdwave/en/2022/01
git mv oilgas-plus.csv /home/burak/Documents/thirdwave/en/2022/01
git mv oilgas.py /home/burak/Documents/thirdwave/en/2022/01
git mv oil.png /home/burak/Documents/thirdwave/en/2022/01
git mv oil-proved-reserves.csv /home/burak/Documents/thirdwave/en/2022/01
git mv oilreserves.png /home/burak/Documents/thirdwave/en/2022/01
git mv opec.png /home/burak/Documents/thirdwave/en/2022/01
git mv pipelines.csv /home/burak/Documents/thirdwave/en/2022/01
git mv pipelines.html /home/burak/Documents/thirdwave/en/2022/01
git mv source-pie.png /home/burak/Documents/thirdwave/en/2022/01
git mv world-crude.csv /home/burak/Documents/thirdwave/en/2022/01
git mv world-energy-combined.png /home/burak/Documents/thirdwave/en/2022/01
git mv worldoil.png /home/burak/Documents/thirdwave/en/2022/01
